### ISSUE TITLE
[Source Request] Dynasty Scans

### ISSUE THREAD

**Issue by BaronKrause** [Paperback-iOS/extensions-promises#126]
Any chance that a source for [Dynasty Scans](https://dynasty-scans.com/) might be added?

Thank you!

**Comment by AdrienSeon** [comment]
Source has been developed, you can find it [here](https://paperback.moe/help/guides/adding-repos/#known-repositories) under the H-extension repository.
Thanks [@PythonCoderAS](https://github.com/PythonCoderAS) for developing it.
