### ISSUE TITLE
[Source Request] myreadingmanga.info

### ISSUE THREAD

**Issue by hazeldng** [Paperback-iOS/extensions-promises#132]
Its a site target female and gay male readers with mostly 18+ contents. 

Thank you so much if you can consider adding this source.

**Comment by AdrienSeon** [comment]
Source has been developed and added to [h-extensions](https://paperback.moe/help/guides/adding-repos/#known-repositories) repositories.

If you have any issue with it, do not hesitate to ask for help on our [discord](https://discord.gg/Ny83JV3) in #support.
