### ISSUE TITLE
[Source Request] skymanga.co

### ISSUE THREAD

**Issue by cookeee3** [Paperback-iOS/extensions-promises#134]

**Comment by cookeee3** [comment]
This site has several 18+ Manhwas from toptoon and other sources released in their raw format daily as well as scanlations from various sources. It also has sfw content.

**Comment by TheNetsky** [comment]
Seems like this is a Madara site.
I've posted this website as a request on the Madara repo.
https://github.com/Paperback-iOS/extensions-madara/issues/10
