### ISSUE TITLE
[Source Request] Asurascans.com

### ISSUE THREAD

**Issue by Tataru-Taru** [Paperback-iOS/extensions-promises#136]
Scanlation group that focuses heavily into Manhwa, they do post on Mangadex too, but its usually days or weeks later.

Sadly doesn't use Madara or Genkan, so can't be hooked into other Promises sources.

**Comment by TheNetsky** [comment]
I got a semi working version of AsuraScans on my [MangaStream repo](https://thenetsky.github.io/extensions-mangastream/).
At the time of writing you need to add the "DEV" branch for AsuraScans! Later this will be added to the stable branch.
