### ISSUE TITLE
[ Source Request]

### ISSUE THREAD

**Issue by alieukf** [Paperback-iOS/extensions-promises#138]
Readcomicsonline.tu

https://readcomiconline.to/

**Comment by AdrienSeon** [comment]
This source has already been implemented, see [https://paperback.moe/help/guides/adding-repos/#known-repositories](https://paperback.moe/help/guides/adding-repos/#known-repositories) to download the corresponding repository in the app 

@ConradWeiser Could we close this one ?

**Comment by FaizanDurrani** [comment]
That's ReadComicsOnline.ru I believe, ReadComicsOnline.to is different

**Comment by AdrienSeon** [comment]
You're right my bad, got baited by the similar name and visual identity.

**Comment by Aur0raN** [comment]
Source has been implemented and is now available in the repo. This issue can be closed,
@FaizanDurrani
