### ISSUE TITLE
[Source Request] Manga Livre

### ISSUE THREAD

**Issue by Ma145** [Paperback-iOS/extensions-promises#157]
https://mangalivre.net/

I think it would be cool to have at least one Portuguese source :smile:

**Comment by Ma145** [comment]
Should I close this to focus on https://github.com/Paperback-iOS/extensions-foreign/issues/13#issue-849401678 ?

**Comment by AdrienSeon** [comment]
Since it's redundant yeah I'll go ahead and close this one, thanks for centralizing your requests there, appreciated.
