### ISSUE TITLE
[Source Request] MangaHub

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/extensions-promises#178]
Website: https://mangahub.io/

**Comment by TheNetsky** [comment]
Source is already complete, you can get it from here.
https://thenetsky.github.io/extensions-promises

**Comment by TheNetsky** [comment]
The reason why it's not included in the main repo is here:
https://github.com/Paperback-iOS/extensions-promises/issues/105

**Comment by PythonCoderAS** [comment]
@TheNetsky Will this be pushed to main when stateful is added?

**Comment by TheNetsky** [comment]
Most likely, yes. Whenever that may be.

**Comment by AdrienSeon** [comment]
Since the source is created and the repo published I'll go ahead and close this one.

We will see in the future when stateful is added if Netsky wants to merge it.

Thank you for your work @TheNetsky
