### ISSUE TITLE
[Bug] App Crash upon Queueing Download. 

### ISSUE THREAD

**Issue by wilsoncai2005** [Paperback-iOS/extensions-promises#196]
Hi Team, 

App crash upon queueing of download below is steps to replicate the issue. I have tried a fresh install and follow the same steps replicates it. 

Replication steps: 

1) Set  ReadcomicsonlineTO as default

2) Open up comic: Invincible (2003). 

3) Queue Download

4) App crashes here after.

**Comment by Aur0raN** [comment]
Any specific chapter as I've downloaded the firt few and it hasn't crashed.

**Comment by wilsoncai2005** [comment]
Hey Aurora, I one shot"marked all" and "download" then crash happened, next I tried 1- 20 also crashed. 

IOS Version: 14.4, Model: MNVP2PP/A 

Paperback Version: V0.5.0 (1.0.6)

**Comment by Aur0raN** [comment]
Does it happen instantly or mid-download the first time you did it as sometimes if the site thinks you're breezing through chapters fast, you would need to go to the site through safari and finish it to allow access, but that wont be the case if it happened instantly on your first time. I'd need to take a look at logs

**Comment by Aur0raN** [comment]
> Hey Aurora, I one shot"marked all" and "download" then crash happened, next I tried 1- 20 also crashed. 
> 
> 
> 
> IOS Version: 14.4, Model: MNVP2PP/A 
> 
> 
> 
> Paperback Version: V0.5.0 (1.0.6) 

Does it happen instantly or mid-download the first time you did it as sometimes if the site thinks you're breezing through chapters fast, you would need to go to the site through safari and finish it to allow access, but that wont be the case if it happened instantly on your first time. I'd need to take a look at logs.

**Comment by ConradWeiser** [comment]
@wilsoncai2005 - I'm having issues replicating this on my end as well. Can you please provide some extra details? @Aur0raN's questions would be a big help.

If this issue is inactive for much longer, we'll temporarily close it. You're more than welcome to open it again if that happens if you're still encountering this issue

**Comment by TheNetsky** [comment]
Since it's been about a month without activity, I'm going to assume this issue has been resolved.
If not, feel free to reopen this issue.
