### ISSUE TITLE
mangagreat.com

### ISSUE THREAD

**Issue by Alanray64** [Paperback-iOS/extensions-promises#198]
This appears to be the originator of a number of manga that other sites scrap from.
Thanks

**Comment by TheNetsky** [comment]
This is a Madara source.
It's already in the list here https://github.com/Paperback-iOS/extensions-madara/issues/24
Not sure when these will be added.

**Comment by AdrienSeon** [comment]
Duplicate of https://github.com/Paperback-iOS/extensions-madara/issues/24
