### ISSUE TITLE
[Source Request] Webtoons

### ISSUE THREAD

**Issue by Cheeseballss** [Paperback-iOS/extensions-promises#204]
https://m.webtoons.com/en/challenge/what-are-the-chances/list?title_no=480113&page=1&webtoon-platform-redirect=true

**Comment by ConradWeiser** [comment]
What an absolute chad to not actually link the website root, but to link a title and page number with your request. 
Unfortunately, this is a duplicate of 
https://github.com/Paperback-iOS/extensions-promises/issues/204
This is already on our list!
