### ISSUE TITLE
[BUG] BatoTo

### ISSUE THREAD

**Issue by TheNetsky** [Paperback-iOS/extensions-promises#246]
As we all know BatoTo has some weird bugs that need some fixing.

Here are some bugs (Feel free to add more in the comments)

- [ ] Chapter dates are not always correct
- [ ] Chapter numbers are (sometimes) incorrect
- [ ] Chapter volumes are sometimes incorrect when the title has "part" in it

Whoever dares to take this task upon themselves, best  of luck!

![image](https://user-images.githubusercontent.com/1227722/118380392-ab3b6e80-b5e1-11eb-81af-52b8a8a55a05.png)

![image](https://user-images.githubusercontent.com/1227722/118380395-af678c00-b5e1-11eb-8e29-7e9cf884eaa6.png)

https://discord.com/channels/673606787290759230/709590204301967375/843854074348568627

**Comment by ConradWeiser** [comment]
Addressed by https://github.com/Paperback-iOS/extensions-promises/pull/254 - Thanks to @Benwor28
