### ISSUE TITLE
[BUG] MangaDex Unlocked excessive requests

### ISSUE THREAD

**Issue by henderea** [Paperback-iOS/extensions-promises#247]
I have the MangaDex unlocked source installed, and several series still bookmarked with it. Recently, whenever I pull down to refresh my manga list, it loads for a really long time before showing an error message. Looking at the logs, I see a TON of requests to MangaDex. It seems to be loading pages of 100 manga at a time, with a pause/interval of 250ms, and apparently it takes so long that the overall refresh times out in the app. 

Here's a snippet from the logs:

```
[INFO] [2021-05-11T12:59:50.995Z] [start():51] [AsyncOperation] Delay Operation - 250ms
://api.mangadex.org/manga?limit=100&offset=6100&updatedAtSince=2021-03-19T21:25:29
[INFO] [2021-05-11T12:59:51.514Z] [start():51] [AsyncOperation] RequestOperation - https://api.mangadex.org/manga?limit=100&offset=6200&updatedAtSince=2021-03-19T21:25:29
[INFO] [2021-05-11T12:59:52.157Z] [start():51] [AsyncOperation] RequestOperation - https://api.mangadex.org/manga?limit=100&offset=6300&updatedAtSince=2021-03-19T21:25:29
```

**Comment by ConradWeiser** [comment]
Thanks for the heads up about this. MangaDex doesn't do updates yet, since they're not allowing new content to be uploaded. This function of the source should probably be removed until they start doing that.

We'll get a patch in within a day or two

**Comment by ConradWeiser** [comment]
As a question following up from the previous snippet, @henderea after an update operation finishes, does it try to search from `2021-03-19T21:25:29` again as you can see in your GET parameters in the logs?

The application should be adjusting to the last finished library update, and using that date instead. Are you stuck on something old for some reason?

**Comment by henderea** [comment]
It's doing March every time. I think it's because it doesn't actually get to finish the entire data load, since the app times it out.

Here's a screenshot of the error popup that happens at the end of the load. Up until the error popup, it says it's loading manga, but it briefly loads chapters at the end apparently. 

![image](https://user-images.githubusercontent.com/657766/118041215-870d3280-b340-11eb-939c-b0a3b54c7868.png)


Here's some error logging:
```
[INFO] [2021-05-12T20:37:20.718Z] [start():51] [AsyncOperation] RequestOperation - https://api.mangadex.org/manga?limit=100&offset=10000&updatedAtSince=2021-03-19T21:25:29
[ERROR] [2021-05-12T20:37:20.894Z] [main():54] [MangaDex] Filter update manga failed [PaperbackError(300)] JSError TypeError: undefined is not an object (evaluating 'json.results') - 
[ERROR] [2021-05-12T20:37:20.896Z] [main():54] generatorResume@[native code]
[ERROR] [2021-05-12T20:37:20.898Z] [main():54] fulfilled
[ERROR] [2021-05-12T20:37:20.900Z] [main():54] promiseReactionJob@[native code]:931:41
```

And actually, looking at the logs, I'm not sure it's a timeout. It looks more like it is missing some error handling or something.

**Comment by ConradWeiser** [comment]
```
[ERROR] [2021-05-12T20:37:20.894Z] [main():54] [MangaDex] Filter update manga failed [PaperbackError(300)] JSError TypeError: undefined is not an object (evaluating 'json.results') - 
```

Thanks for sending your logs with the Git issue, this is perfect. I can verify that there's some functions which attempt to parse a JSON response from the API with: 
```
 const json = typeof response.data === "string" ? JSON.parse(response.data) : response.data
```
But it doesn't check if `json.results` is undefined or not before trying to use it. We can likely edit that to include some graceful-handling, where if it's undefined, simply return what it's got successfully or return like it's supposed to. 

Thanks, I'll update this issue with how things go. I'd love if you'd be willing to test it as I'm not able to replicate your conditions outside of Typescript Tests very easily.

**Comment by henderea** [comment]
Well, it isn't getting an error anymore, but it still takes a _really_ long time to refresh the manga list. I think it's still loading those 80+ pages of the listing (100/page, 8k+ results).

**Comment by ConradWeiser** [comment]
The issue isn't entirely resolved. The system simply needs to refresh and load through all of the results ONCE, and it should work great in the future.
Unfortunately, as soon as you hit offset 10,000, MangaDex returns a failure, and the app aborts the update procedure. I've had a conversation with some MangaDex developers, this is a known problem on their end that they're trying to resolve.

**Comment by ConradWeiser** [comment]
For now, we've disabled update checking entirely. MangaDex isn't uploading new content just yet anyways. 
Once we're sure that their API is a little less quirky (as having to go up to an offset of 10,000 is an awfully big number for 2 months where nothing has been uploaded in those two months) - We'll reenable the functionality and ensure that things work again properly.

Until then, at least with this update, a library update operation won't take forever for your other sources.
