### ISSUE TITLE
[Bug] Manganelo 

### ISSUE THREAD

**Issue by ConradWeiser** [Paperback-iOS/extensions-promises#257]
Sometimes Manganelo likes to simply stop working. 
* Opening a chapter will give a `[start():51] [AsyncOperation] RequestOperation - https://manganelo.com/chapter/` URL sometimes which isn't valid, causing a crash
* Update checking is known to not function correctly. 

https://discord.com/channels/673606787290759230/702052855623843861/846745230732820500

Reference the link above for conversation about this, along with some videos of Manganelo failing. (You must be in the Paperback discord to navigate to the above link)

More detailed information is required

**Comment by TheNetsky** [comment]
As stated before, sometimes the Manganelo URL will just end at `/chapter/` this is also the case for downloads, causing them to fail. (and sometimes crash the app?)

[Conversation Here](https://discord.com/channels/673606787290759230/702052855623843861/846848745160441896)

![image](https://user-images.githubusercontent.com/56271887/119567478-a8dccf80-bdac-11eb-872d-e3bc961d354a.png)

**Comment by TheNetsky** [comment]
Some manga will fail on getting manga Details
Example: https://manganelo.com/manga/oj925394

Error being thrown:
`[INFO] [2021-05-26T15:24:58.625Z] [start():51] [AsyncOperation] RequestOperation - https://manganelo.com
[INFO] [2021-05-26T15:25:12.004Z] [loadManga(sourceId:mangaId:):324] Fetched oj925394 (Manganelo from Library
[INFO] [2021-05-26T15:25:12.379Z] [start():51] [AsyncOperation] Delay Operation - 400ms
://manganelo.com/manga/
[ERROR] [2021-05-26T15:25:12.772Z] [loadChapters():60]  [PaperbackError(300)] JSError TypeError: undefined is not an object (evaluating 'node.parent') - 
[ERROR] [2021-05-26T15:25:12.778Z] [loadChapters():60] generatorResume@[native code]
[ERROR] [2021-05-26T15:25:12.781Z] [loadChapters():60] fulfilled
[ERROR] [2021-05-26T15:25:12.784Z] [loadChapters():60] promiseReactionJob@[native code]:1813:25
[INFO] [2021-05-26T15:25:25.728Z] [reloadSources():48] Loading WebtoonXYZ version: 1.1.2`

**Comment by TheNetsky** [comment]
Since most of these bugs have been fixed with the new Manganelo for 0.5 and the fact that 0.6 uses MangaBox for the new Manganelo/Manganato, I'll close this issue.
