### ISSUE TITLE
[BUG] Chapter order on new MangaDex source

### ISSUE THREAD

**Issue by henderea** [Paperback-iOS/extensions-promises#289]
I encountered an issue with the order of chapters on a series with the new MangaDex extension (2.0.5). I couldn't find the GitHub repo for it, so I'll post it here and can repost it in the right place if I'm told where. 

![image](https://user-images.githubusercontent.com/657766/125169022-539b2880-e176-11eb-824e-0b6ff0723498.png)

I'm not really sure what's up with the chapter order here. It's pretty wacky. Btw, the series (Sacred Chevalier) is more on the mature side, probably the second highest rating, so you would need to change those settings to see it for testing.

I would think the chapters would be sorted by number. Btw, I have the chapter sort order set to descending.

**Comment by FaizanDurrani** [comment]
Chapters without a volume are considered as "ongoing volume" and are sorted to the top. This is how MangaDex shows the chapters and isn't the fault of the app.
