### ISSUE TITLE
[BUG] Lots of errors with MangaDex source

### ISSUE THREAD

**Issue by henderea** [Paperback-iOS/extensions-promises#292]
I'm getting lots of error popups and issues with the latest MangaDex source 2.0.7. The search isn't working for me, and the browse tab isn't working either. I also see an error popup when I try to "refresh" the source:

```
[INFO] [2021-07-15T22:46:28.512Z] [JavaScriptModel:init(for:mainFileLocation:):62] Initialised Extension: MangaDex - 2.0.7 by nar1n
[ERROR] [2021-07-15T22:46:29.137Z] [SourceModelImplementation:getHomepageSections(callback:):84] JSError Error JSError Error
[ERROR] [2021-07-15T23:02:52.809Z] [SourceModelImplementation:getHomepageSections(callback:):84] JSError Error JSError Error
[ERROR] [2021-07-15T23:04:34.824Z] [SourceModelImplementation:getHomepageSections(callback:):84] JSError Error JSError Error
```

Getting and reading updates for series I've already bookmarked still works fine.

**Comment by TheNetsky** [comment]
Hi, if you're on the latest 0.6 beta. 

1. Go to the MangaDex source, 
2. Click the "Reset to defaults" button
3. Re enable your proffered content demographics.

**Comment by henderea** [comment]
Ah, that fixed it. Guess it was the removal of the unknown demographic that messed stuff up.
