### ISSUE TITLE
[Source Standardization] - Implementation of update functions

### ISSUE THREAD

**Issue by ConradWeiser** [Paperback-iOS/extensions-promises#44]
Currently, paperback uses a method called filterUpdatedManga(id, dateRange) method in order to determine whether a manga has been updated since the user has last looked at it.

The goal of this method is to simply take a date, and scan for if any of the supplied IDs has been updated since then. 
Ideally, this should be implemented in every source if possible.

- [x] IsekaiScan - Removed from content listing
- [x] MangaDex
- [x] MangaFox - Implemented
- [x] MangaLife - Implemented
- [x] Manganelo - Implemented
- [x] MangaPark - Implemented
- [x] Mangasee - Implemented
- [x] nHentai (Doesn't require updates)
- [x] nHentai - Redirector (Doesn't require updates)
- [ ] Webtoons

**Comment by ConradWeiser** [comment]
Webtoons is going to be a tricky one. There's no page which lists all titles which have been recently updated. There is no RSS feed which can be tapped off of either. 

A potential alternative might be appending the update schedule to the description of each toon, and not implementing the app notifications for it.

**Comment by FaizanDurrani** [comment]
@ConradWeiser if you just return null in the request method, it will force check for updates on all manga from webtoon source in the library.

**Comment by AdrienSeon** [comment]
Issue seams outdated now, closing this one
