### ISSUE TITLE
[Suggestion] Get Source Directory

### ISSUE THREAD

**Issue by ConradWeiser** [Paperback-iOS/extensions-promises#68]
### What is being suggested
A function in Source.ts (Optional) which when called, will start to return as much content as it can. Likely sorted from a list of popularity on the source itself.

This method will likely need to make multiple calls somehow. Traversing through multiple pages, as the source is stepped through.

### What could be implemented on the application due to this
A section could be added to the application which shows a popularity list on the source itself. This could be useful for discovering new manga, as the current home sections are a big of a pain in the ass to traverse through. Having a source-specific page, which perhaps is a large grid of MangaTiles may be a better experience for the user.

**Comment by ConradWeiser** [comment]
Implementation pending approval from @FaizanDurrani - Likely will not be a priority

**Comment by FaizanDurrani** [comment]
This is likely planned for b11 or later.

**Comment by AdrienSeon** [comment]
Feature has been implemented when Promises where pushed https://github.com/Paperback-iOS/extensions-common/pull/14
