### ISSUE TITLE
[Source Request] manhuaplus.com

### ISSUE THREAD

**Issue by james43440** [Paperback-iOS/extensions-promises#92]

**Comment by ConradWeiser** [comment]
I could have sworn that there was a reason this source wasn't considered previously. Although now that I'm looking into the source again, I can't really find any issues. 

Are you convinced that the contents on this source contains Manhwa that another source doesn't already have? (Is this one more up to date? Does this one have a massive list of content?)

**Comment by ConradWeiser** [comment]
On another look, Toonily.com seems to be focused on more mature titles. Some big Manhwa (Such as Immortal God Emperor and others) did not show up on that website, but did appear on Manhwaplus.

Marking this as an enhancement!

**Comment by GameFuzzy** [comment]
It's a generic Madara source

**Comment by AdrienSeon** [comment]
Source has been developed, check [this repo](https://paperback-ios.github.io/extensions-madara) or [this page](https://paperback.moe/help/guides/adding-repos/) from your iOS device and add Madara Extensions repo.

Closing this one
